fix: some vulnerabilities
yeoman/yo pull request #717
Opened 2021-12-06 21:52 UTC by Florian-Schoenherr

## Purpose of this pull request? 

- [ ] Documentation update
- [X] Bug fix 
- [ ] Enhancement
- [ ] Other, please explain:

## What changes did you make?

Fixed some of the security vulnerabilities, the others depend on some of the PRs in sub repos.

## Is there anything you'd like reviewers to focus on?

I removed the "pretest": "xo" script for now, as it doesn't work. I think temporarily removing it is better than keeping a high security vulnerability around. This is the error when keeping it:
![image](https://user-images.githubusercontent.com/65456722/144928053-f96bbeb5-8e40-4562-bd03-ad4365bece5e.png)
the cut line says `Cannot find package 'D:\...\yo\node_modules\xo\node_modules\eslint\' imported from D:\...\yo\node_modules\xo\index.js`

2021-12-06 21:55 UTC, Florian-Schoenherr commented
oh and I replaced got with node-fetch, which wasn't really necessary here, could be reverted, too.
Although does the fetch right there even work? If I just go on that link it gives back a 404 page.

2021-12-06 22:30 UTC, mshima requested changes

2021-12-06 22:30 UTC, mshima commented on package.json
> -    "pretest": "xo",
We should keep pretest script.

2021-12-06 22:30 UTC, mshima commented on package.json
> +    "xo": "^0.47.0"
```suggestion
    "xo": "0.38.0"
```
There are security problems, but this is dev only, won’t be a problem for npm install yo.
Version 0.40.0 is esm only. So 0.39.x should be to newest possible.

2024-12-20 18:18 UTC, UlisesGascon commented
It looks like this has been inactive for some time, so we're going to go ahead and close it for now to keep the repo tidy.

If you'd like to revisit this or have any updates to share, please feel free to reopen the PR or create a new one—your contributions are always welcome @Florian-Schoenherr!

2024-12-20 18:18 UTC, closed without merging